export const events = [
  {
    id: 1,
    clubname: "Chess Club",
    location: "Community Center, Room 101",
    date: "2025-09-10",
    time: "18:00",
    type: "Tournament",
    numberofparticipant: 20,
    status: "upcoming",
  },
  {
    id: 2,
    clubname: "Book Club",
    location: "City Library",
    date: "2025-08-15",
    time: "19:30",
    type: "Discussion",
    numberofparticipant: 12,
    status: "completed",
  },
  {
    id: 3,
    clubname: "Running Club",
    location: "Central Park",
    date: "2025-09-20",
    time: "07:00",
    type: "Group Run",
    numberofparticipant: 35,
    status: "upcoming",
  },
  {
    id: 4,
    clubname: "Photography Club",
    location: "Downtown Studio",
    date: "2025-07-25",
    time: "14:00",
    type: "Workshop",
    numberofparticipant: 15,
    status: "completed",
  },
  {
    id: 5,
    clubname: "Coding Club",
    location: "Tech Hub, Lab 3",
    date: "2025-10-05",
    time: "17:00",
    type: "Hackathon",
    numberofparticipant: 40,
    status: "upcoming",
  },
  {
    id: 6,
    clubname: "Art Club",
    location: "Art Gallery, Studio B",
    date: "2025-09-05",
    time: "15:00",
    type: "Painting Session",
    numberofparticipant: 10,
    status: "upcoming",
  },
  {
    id: 7,
    clubname: "Music Club",
    location: "Concert Hall",
    date: "2025-08-20",
    time: "20:00",
    type: "Jam Session",
    numberofparticipant: 25,
    status: "completed",
  },
  {
    id: 8,
    clubname: "Debate Club",
    location: "University Hall",
    date: "2025-10-12",
    time: "16:30",
    type: "Debate Competition",
    numberofparticipant: 30,
    status: "upcoming",
  },
  {
    id: 9,
    clubname: "Gardening Club",
    location: "Community Garden",
    date: "2025-07-30",
    time: "09:00",
    type: "Planting Workshop",
    numberofparticipant: 18,
    status: "completed",
  },
  {
    id: 10,
    clubname: "Yoga Club",
    location: "Wellness Center",
    date: "2025-09-15",
    time: "06:30",
    type: "Morning Yoga",
    numberofparticipant: 22,
    status: "upcoming",
  },
];
