export const dummyUsers = [
  {
    id: "LS8 3DN",
    name: "Guy Hawkins",
    clubName: "Manchester United",
    status: "Active",
    ghinNumber: "GH123456",
    handicapIndex: 5.4,
    country: "United Kingdom",
    state: "England",
    gender: "Male",
    dateOfBirth: "1990-03-12",
    address: "12 King Street, Manchester, M1 2AB",
    email: "guy.hawkins@example.com",
  },
  {
    id: "CH66 2RD",
    name: "Cameron Williamson",
    clubName: "Chelsea",
    status: "Active",
    ghinNumber: "GH234567",
    handicapIndex: 8.2,
    country: "United Kingdom",
    state: "England",
    gender: "Male",
    dateOfBirth: "1988-07-25",
    address: "45 Queen Road, London, SW1A 1AA",
    email: "cameron.williamson@example.com",
  },
  {
    id: "FK6 6NA",
    name: "Kathryn Murphy",
    clubName: "Liverpool",
    status: "Active",
    ghinNumber: "GH345678",
    handicapIndex: 12.0,
    country: "United Kingdom",
    state: "England",
    gender: "Female",
    dateOfBirth: "1992-11-04",
    address: "67 Albert Dock, Liverpool, L1 8JQ",
    email: "kathryn.murphy@example.com",
  },
  {
    id: "RM10 9DG",
    name: "Darrell Steward",
    clubName: "Arsenal",
    status: "Banned",
    ghinNumber: "GH456789",
    handicapIndex: 9.5,
    country: "United Kingdom",
    state: "England",
    gender: "Male",
    dateOfBirth: "1985-05-18",
    address: "22 Holloway Road, London, N7 8DB",
    email: "darrell.steward@example.com",
  },
  {
    id: "G72 7ND",
    name: "Marvin McKinney",
    clubName: "Tottenham",
    status: "Banned",
    ghinNumber: "GH567890",
    handicapIndex: 14.1,
    country: "United Kingdom",
    state: "England",
    gender: "Male",
    dateOfBirth: "1993-02-28",
    address: "89 High Road, Tottenham, N17 0AP",
    email: "marvin.mckinney@example.com",
  },
  // ...continue for the rest
];
